name: Update RU Geosites Ruleset

on:
  schedule:
    - cron: '0 4 * * *' # Будет запускаться каждый день в 04:00 UTC
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install compatible sing-box compiler (v1.9.3)
        run: |
          # Скачиваем совместимую с Hiddify-core v4.1.0 версию
          wget -O sing-box.tar.gz "https://github.com/SagerNet/sing-box/releases/download/v1.9.3/sing-box-1.9.3-linux-amd64.tar.gz"
          tar -xzf sing-box.tar.gz
          sudo cp sing-box-*/sing-box /usr/local/bin/
          sing-box version

      - name: Download JSON and Compile to SRS
        run: |
          # 1. Скачиваем исходный JSON
          wget -O geosites_ru.json "https://raw.githubusercontent.com/sudmed/podkop/refs/heads/main/geosites_ru.json"
          
          # 2. Компилируем в бинарный формат
          sing-box rule-set compile geosites_ru.json -o geosites_ru.srs

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Индексируем скачанный JSON и собранный SRS
          git add geosites_ru.json geosites_ru.srs
          
          git commit -m "Auto-update RU Geosites (JSON + SRS)" || echo "No changes to commit"
          git push || echo "No changes to push"
